# Generated by Django 3.2.6 on 2021-08-18 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cancion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('id_externo', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('album', models.CharField(max_length=255)),
                ('banda', models.CharField(max_length=255)),
                ('duracion', models.CharField(max_length=255)),
                ('genero', models.CharField(max_length=255)),
                ('subgenero', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Cancion',
                'verbose_name_plural': 'Canciones',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cancion')),
            ],
            options={
                'verbose_name': 'Label',
                'verbose_name_plural': 'Labels',
            },
        ),
        migrations.CreateModel(
            name='Instrumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cancion')),
            ],
            options={
                'verbose_name': 'Instrumento',
                'verbose_name_plural': 'Instrumentos',
            },
        ),
        migrations.CreateModel(
            name='BandasSimilares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cancion')),
            ],
            options={
                'verbose_name': 'Banda Similar',
                'verbose_name_plural': 'Bandas similares',
            },
        ),
        migrations.CreateModel(
            name='Artista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('cancion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.cancion')),
            ],
            options={
                'verbose_name': 'Artista',
                'verbose_name_plural': 'Artistas',
            },
        ),
    ]
